#!/usr/bin/python
#
# Created by Aaron Beckett January, 2016
#

import sys

from ctip_utils import CTIPError
import ctip_commands as ctip

helpText = """
./ctip <command> <args>

COMMANDS:

    run:    ./ctip run [OPTIONS] <config_table_name> ["<sql_where_clause>"]
                            OR
            ./ctip run [OPTIONS] -f <config_file> ["<sql_where_clause>"]

    gen:    ./ctip gen <gen_config_file>

    tables: ./ctip tables

    list:   ./ctip list <table_name> ["<sql_where_clause>"]

    save:   ./ctip save [-o <out_file>] <table_name>

    check:  ./ctip check [<session_id>]

    clean:  ./ctip clean [<session_id>]

    update: ./ctip update-status <job_id> <status>
            ./ctip update-id <job_id> <new_id>

    log:    ./ctip log-start <job_id>
            ./ctip log-pause <job_id>
            ./ctip log-resume <job_id>
            ./ctip log-end <job_id>

OPTIONS:

    -o, --outdir:
        Specify in which directory the test session folder should be placed.
        By default the session directory will be placed in a folder named
        after its config table and located in the root ctip directory.

    -q, --qsub:
        Specify which qsub template should be used when sumbitting jobs
        for this test session.

    -n, --name:
        Provide a name for this test session. The name will be appended
        the the end of the default session directory name which is a
        date-time string.
"""

def main(argv):
    try:
        command = argv[1]

        if command == "run":
            ctip.run(argv[2:])
        elif command == "gen":
            ctip.gen(argv[2:])
        elif command == "tables":
            ctip.tables(argv[2:])
        elif command == "list":
            ctip.list(argv[2:])
        elif command == "save":
            ctip.save(argv[2:])
        elif command == "check":
            ctip.check(argv[2:])
        elif command == "clean":
            ctip.clean(argv[2:])
        elif command == "update-status":
            ctip.update_status(argv[2:])
        elif command == "update-id":
            ctip.update_id(argv[2:])
        elif command == "log-start":
            ctip.log_start(argv[2:])
        elif command == "log-pause":
            ctip.log_pause(argv[2:])
        elif command == "log-resume":
            ctip.log_resume(argv[2:])
        elif command == "log-end":
            ctip.log_end(argv[2:])
        else:
            raise CTIPError("No CTIP command named '" + command + "'.")

    except IndexError, RuntimeError:
        print(helpText)
        sys.exit(2)

    except CTIPError as e:
        print(e.msg)
        
if __name__ == "__main__":
    main(sys.argv)

