#!/bin/bash -login
#PBS -l walltime=00:10:00,nodes=1:ppn=1,mem=1MB
#PBS -j oe
#PBS -N %=job_name
#PBS -o %=shell_out_file
cd ${PBS_O_WORKDIR}

CTIP="/mnt/home/becketta/MarkovBrain/testing/ctip-tool/ctip"

EXAMPLE_SCRIPT="/mnt/home/becketta/MarkovBrain/testing/ctip-tool/example_job.py"
WAIT_TIME="%=wait_time"
RUN_CONFIG="%=config_file"

$EXAMPLE_SCRIPT -t $WAIT_TIME -f $RUN_CONFIG

# Tell ctip the job is done
$CTIP status ${PBS_JOBID} done

echo
qstat -f ${PBS_JOBID}

